### ISSUE TITLE
NameError: name 'q' is not defined at blam.py:1300

### ISSUE THREAD

**Issue by FirefighterBlu3** [Blue-Labs/Blam#14]
``` log
01:33:21 I 0.0  10.255.0.4:39070 switching iolog stream to /var/spool/blam/logfiles/BC50311DC4C
01:33:22 E 0.0                   unhandled exception in read_milter_data: name 'q' is not defined
01:33:22 E 0.0                   Traceback (most recent call last):
```

``` python
  File "/var/bluelabs/utils/blam.py", line 2040, in _run_header_tests
    netaddr.IPAddress(v)
  File "/usr/lib/python3.5/site-packages/netaddr/ip/__init__.py", line 306, in __init__
    'address from %r' % addr)
netaddr.core.AddrFormatError: failed to detect a valid IP address from 'mxdalpv02i.wellsfargo.com.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/bluelabs/utils/blam.py", line 1298, in check_dnsbl_by_name
    answers = self.resolver.query(addr, 'A')
  File "/usr/lib/python3.5/site-packages/dns/resolver.py", line 774, in query
    qname = dns.name.from_text(qname, None)
  File "/usr/lib/python3.5/site-packages/dns/name.py", line 613, in from_text
    raise EmptyLabel
dns.name.EmptyLabel

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ppymilter/server.py", line 193, in read_milter_data
    response = self.__milter_dispatcher.Dispatch(inbuff)
  File "/usr/lib/python3.5/site-packages/ppymilter/base.py", line 158, in Dispatch
    return callback(*args)
  File "/var/bluelabs/utils/blam.py", line 2711, in OnEndBody
    _ = self._run_header_tests(msg)
  File "/var/bluelabs/utils/blam.py", line 2044, in _run_header_tests
    _ = self.check_dnsbl_by_name(v)
  File "/var/bluelabs/utils/blam.py", line 1300, in check_dnsbl_by_name
    except Exception as e: self.printme('problem resolving {}: {}'.format(q, e), console=True)
NameError: name 'q' is not defined
```

**Comment by FirefighterBlu3** [comment]
resolved by ebf31e4
