### ISSUE TITLE
xml.dom.SyntaxErr: Selector: Cannot end with combinator

### ISSUE THREAD

**Issue by FirefighterBlu3** [Blue-Labs/Blam#20]
``` log
07:02:39 E 0.0                   unhandled exception in read_milter_data: Selector: Cannot end with combinator: .content-td > 
07:02:39 E 0.0                   Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ppymilter/server.py", line 193, in read_milter_data
    response = self.__milter_dispatcher.Dispatch(inbuff)
  File "/usr/lib/python3.5/site-packages/ppymilter/base.py", line 158, in Dispatch
    return callback(*args)
  File "/var/bluelabs/utils/blam.py", line 2784, in OnEndBody
    self._run_body_tests(msg)
  File "/var/bluelabs/utils/blam.py", line 2531, in _run_body_tests
    rule._setSelectorText(re.sub(':[\w_-]+','', rule.selectorText))
  File "/usr/lib/python3.5/site-packages/cssutils/css/cssstylerule.py", line 206, in _setSelectorText
    sl = SelectorList(selectorText=selectorText, parentRule=self)
  File "/usr/lib/python3.5/site-packages/cssutils/css/selectorlist.py", line 43, in __init__
    self.selectorText = selectorText
  File "/usr/lib/python3.5/site-packages/cssutils/css/selectorlist.py", line 198, in _setSelectorText
    parent=self)
  File "/usr/lib/python3.5/site-packages/cssutils/css/selector.py", line 121, in __init__
    self.selectorText = selectorText
  File "/usr/lib/python3.5/site-packages/cssutils/css/selector.py", line 772, in _setSelectorText
    % self._valuestr(selectorText))
  File "/usr/lib/python3.5/site-packages/cssutils/errorhandler.py", line 98, in __handle
    raise error(msg)
xml.dom.SyntaxErr: Selector: Cannot end with combinator: .content-td >
```

**Comment by FirefighterBlu3** [comment]
probably /var/spool/blam/logfiles/0C96F11F084

**Comment by FirefighterBlu3** [comment]
no body content available, unable to investigate at this time. code added to store on-disk payloads as soon as OnEndBody() is called
